### ISSUE TITLE
Problema ao selecionar a topologia da rede

### ISSUE THREAD

**Issue by Arthur-Negrao-Smith** [quantumgercom/QuantumNet#2]
## Descrição do problema 
Ao criar a rede e tentar selecionar a topologia da mesma com a função set_ready_topology, a execução para com um TypeErro
![image](https://github.com/user-attachments/assets/dd3ad346-4fea-411c-9f12-5aacfd5f96b2)
## Erro que aparece
![image](https://github.com/user-attachments/assets/83d4fbf5-1ffa-4f30-a146-552ca7046857)
## Adendo
Esse erro também acontece quando tento rodar os códigos Guia do simulador

**Comment by quantumgercom** [comment]
Erro ocorria pela falta de um argumento na função de registrar qubit criado. A função foi corrigida.
